name: MCX Crude Oil Indian Price Alert

on:
  workflow_dispatch:

  schedule:
    # Monday–Friday
    # 09:00 AM–11:30 PM India time
    # GitHub cron works only in UTC
    - cron: "*/15 4-17 * * 1-5"
    - cron: "30 3 * * 1-5"
    - cron: "0,15,30 18 * * 1-5"
